name: "Buld and Test docs"
description: ""

inputs:
  TEMP_DIR:
    description: "Directory for temporary files and artifacts"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Setup environment"
      shell: "bash"
      run: |
        poetry install

    - name: "Ensure latest docs build without warning or errors"
      shell: "bash"
      run: >-
        poetry install -E docs &&
        poetry run sphinx-build -W --keep-going docs docs/_build/html

    - name: "Check for broken links in the docs"
      shell: "bash"
      run: |
        poetry run sphinx-build -b linkcheck docs docs/_build/linkcheck

    # Build docs and push to gh-pages
    - name: "Build docs and push to gh-pages"
      shell: "bash"
      run: >-
        poetry run bin/sphinx_push_ghpages.sh
