import logging


ASYNC=False
MAX_RETRIES = 4
DEFAULT_LOG_LEVEL = logging.WARNING  # change to DEBUG for more detail
MAX_QUERIES_PER_SECOND = 10
CROP_CALENDAR_METRIC_ID = 2260063
TIMEOUT=6000
MAX_RESULT_COMBINATION_DEPTH=3
