import logging


MAX_RETRIES = 4
DEFAULT_LOG_LEVEL = logging.INFO  # change to DEBUG for more detail
MAX_QUERIES_PER_SECOND = 10
TIMEOUT=6000
MAX_RESULT_COMBINATION_DEPTH=3
MAX_DATA_SERIES_PER_COMB=1000
