---

version: 2.1

jobs:
  ci:
    # ref: https://circleci.com/docs/2.0/executor-types/?section=executors-and-images#using-docker
    docker:
      # Use the base circle CI image
      - image: "cimg/python:3.7"
    steps:
      # TODO set up source and pip caching
      # checkout the git repo
      - checkout

      - run:
          name: "Environment setup"
          command: |
            pip install -U pip wheel
            pip install poetry
            poetry install

      - run:
          name: "Run doctests"
          command: poetry run python groclient/lib.py -v

      - run:
          name: "Run tests and code coverage"
          command: >-
            mkdir -p circleci/testresults circleci/codecoverage &&
            poetry run pytest
            --junitxml=circleci/testresults/junit.xml
            --cov=groclient
            --cov-report=html:circleci/codecoverage/coverage_html

      - store_test_results:
          path: circleci/testresults

      - store_artifacts:
          path: circleci/codecoverage/coverage_html
      
      - run:
          name: "Test sample notebook"
          command: >-
            poetry run pip install -r api/client/samples/analogous_years/requirements.txt &&
            poetry run pytest api/client/samples/analogous_years/

      # We'll skip conditionally checking for success at this point since by default
      # CircleCI will run the following steps on_success
      # https://circleci.com/docs/2.0/configuration-reference/#run
      - run:
          name: "Ensure latest docs build without warnings or errors"
          command: >-
            poetry install -E docs &&
            poetry run sphinx-build -W --keep-going docs docs/_build/html

      - run:
          name: "Check for broken links in the docs"
          command: |
            poetry run sphinx-build -b linkcheck docs docs/_build/linkcheck

      # Build docs and push to gh-pages.
      # Note: git remote set-url is for setting a git url instead of an https
      # one, which is needed so Shippable can be authenticated to push changes.
      - run:
          name: "Build docs and push to gh-pages"
          command: >-
            git config --global user.email "api-documentation@gro-intelligence.com" &&
            git config --global user.name "Gro Intelligence" &&
            git remote set-url origin git@github.com:$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git &&
            poetry run bin/sphinx_push_ghpages.sh

      # Note: We need to install versioning library outside of the poetry venv.
      # See note in CONTRIBUTING.md.
      - run:
          name: "Build package"
          command: >-
            pip install poetry-dynamic-versioning &&
            poetry build

      # Publish new development updates to TestPyPI whenever changes are merged
      # to development.
      # We only want to publish a new package when PRs are actually accepted and
      # merged, which is why we check $CIRCLE_PULL_REQUEST.
      - run:
          name: "Push to testpypi"
          command: >-
            if [ "$CIRCLE_BRANCH" == "development" ] && [ -z "$CIRCLE_PULL_REQUEST" ]; then
              poetry config repositories.testpypi https://test.pypi.org/legacy/ &&
              poetry publish -u __token__ -p $TESTPYPI_TOKEN -r testpypi
            fi

      # Publish new releases to PyPI.
      # We only check whether this is a tagged build and if so, publish to pypi
      # Check that $CIRCLE_TAG is not a null string
      - run:
          name: "Push to pypi"
          command: >-
            if [ -n "$CIRCLE_TAG" ]; then
              poetry publish -u __token__ -p $PYPI_TOKEN
            fi

    environment:
      GROAPI_TOKEN: dummytoken

workflows:
  ci-workflows:
    jobs:
      - ci:
          filters:
            tags:
              only: /^v.*/

